# Generated by Django 5.1.7 on 2025-03-17 09:12

import backend.apps.core.db.mixins.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_person_created_at_alter_person_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="phone",
            field=backend.apps.core.db.mixins.fields.PhoneField(
                max_length=15, unique=True
            ),
        ),
    ]
